name: Checks

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system libs
        run: sudo apt-get install libasound2-dev libudev-dev pkg-config
      - name: Run clippy
        run: cargo clippy -- -Dwarnings
