name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Lint
            cmd: |
              cargo clippy -- -Dwarnings
              cargo fmt --all -- --check
          - name: Build
            cmd: |
              cargo build
              cargo build --examples
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          save-always: true
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: Install system libs
        run: sudo apt-get install libasound2-dev libudev-dev pkg-config
      - name: ${{ matrix.name }}
        run: ${{ matrix.cmd }}
